language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
  - rbx
  - jruby-18mode
  - jruby-19mode
script: bundle exec rake test
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.1.x
  - Gemfile
before_install:
  - (ruby -v | grep -q 1.8.7 && gem update --system 2.1.11) || true
install: "bundle install"
matrix:
  exclude:
    - rvm: 1.8.7 
      gemfile: Gemfile
    - rvm: 1.8.7 
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: ree
      gemfile: Gemfile
    - rvm: ree
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
